theme: jekyll-theme-minimal
title: Welcome to Sahil's homepage !
author: PhD Student, Electrical and Computer Engineering, Boston University
author_email: tikale@bu.edu, sahil.tikale@gmail.com
description: Feel free to bookmark this to keep an eye on my project updates.


